### ISSUE TITLE
Add-In does not load in current VS Code Insiders version

### ISSUE THREAD

**Issue by lafe** [hediet/vscode-drawio#101]
After updating to the current Insiders version of VS Code, the Draw.io Add-In does not work anymore and shows the following message:
![image](https://user-images.githubusercontent.com/4070008/85528856-bd4ca100-b60c-11ea-9767-f71197edfbda.png)

The message states that it might related to https://github.com/microsoft/vscode/issues/89038, but there seems to be no change in that item. However, it seems that https://github.com/microsoft/vscode/issues/100918 as it also deals with webviews and relates to todays Insider build.

Version information:
Version: 1.47.0-insider (user setup)
Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69
Date: 2020-06-23T09:03:35.861Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by hediet** [comment]
Have you tried reloading/reopening the file/vscode? Is it consistenly broken?

Thanks for opening the VS Code issue!
Seems like this is a general bug in VS Code in the current vs code insiders.

**Comment by lafe** [comment]
It is consistently broken and reproducible across multiple machines (I tested it on my work and my private machine and a colleague tested it on his work machine as well).

**Comment by hediet** [comment]
Thanks a lot for your research/experimentation ;)
Yeah, I think tracking the issue here too is a good thing!

**Comment by lafe** [comment]
The issue is fixed in the current Insiders version.

**Comment by Ciantic** [comment]
It doesn't work with stable vscode. Is this also intentional at the moment?

I tried to create empty file `architecture.dio`. Then I tried to reload the window many times. 

![image](https://user-images.githubusercontent.com/64731/85957260-9ab3e280-b994-11ea-9960-6df8fb4f835b.png)

![image](https://user-images.githubusercontent.com/64731/85957271-a99a9500-b994-11ea-9086-c65dadf0af0e.png)

![image](https://user-images.githubusercontent.com/64731/85957291-d5b61600-b994-11ea-82b7-f8aa44017fab.png)

**Comment by hediet** [comment]
This is not intentional. However, it does work for me:
![image](https://user-images.githubusercontent.com/2931520/85960170-e8831780-b9a1-11ea-9897-42de5890aba5.png)

Can you open a new issue and give more details so I can reproduce it?

Have you tried to close and reopen the tab (not the entire process)?
