### ISSUE TITLE
Request: Publish Extension on open-vsx.org for VSCodium users

### ISSUE THREAD

**Issue by ChrisCrossQS** [hediet/vscode-drawio#110]
Hi Hediet,

currently the extension is available on the Microsoft VS Code marketplace.
VS Codium (VS Code without MS telemetry, link for more details: https://github.com/VSCodium/vscodium/blob/master/DOCS.md)
uses the open-vsx.org marketplace (Eclipse Foundation) instead. This has an adapter for MS VS Code Marketplace, but currently your extension is not available in VS Codium using open-vsx. Would it be possible for you, to post the extension also to open-vsx.org? Alternatively the extension could be added here: https://github.com/open-vsx/publish-extensions. They would then publish it in a nightly run.

Thanks for your feedback
Chris

**Comment by hediet** [comment]
I will consider this if this issue gets 10 upvotes!
Also, telemetry is a good thing... Especially when you have to triage a lot because the work power does not cover the feature demand, telemetry helps do prioritize for the important things.

**Comment by HansUXdev** [comment]
I'm trying to do this right now for the auth0 hackathon. 
@hediet I love the "will do for sponsorship". 

I feel that for sure. I'm trying to use GitPod for educational modules and would love this extension forked over so people can communicate and collaborate visually on things.

**Comment by hediet** [comment]
Thanks ;) Why do you need this extension to be forked? How does open-vsx relate to git pod?
What are you trying to do? ;)

**Comment by HansUXdev** [comment]
So to my understanding, GitPod is built on top of theia ide and uses open-vsx because due to the pseudo-open-source nature of the vscode marketplace, they can't add them from marketplace.

The challenge for the hackathon is to improve connectivity because coworkers, etc and so having draw.io on the here would allow me to communicate with designers in a shared remote environment about design decisions and architecture.

Here is the hackathon repo: https://github.com/HansUXdev/RemoteDevCatz
There are more than a few images made by draw.io

**Comment by hediet** [comment]
Sadly, Theia does not seem to support custom editors yet. So this extension is not compatible with theia anyways! Publishing to open-vsx does not help here.

**Comment by HansUXdev** [comment]
Does this also apply for VS Codium? I'm not 100% sure what you mean by it not supporting custom editors.
https://dev.to/svenefftinge/theia-1-0-finally-a-good-browser-ide-3ok0

I glanced at the source but haven't done a deep dive.

Also your docs mention:
https://github.com/fjudith/docker-draw.io

Since GitPod is built on top of docker, I wonder if that could be another way of approaching the problem?

I'm also not opposed to starting from scratch using something like this:
https://www.npmjs.com/package/generator-theia-extension

However, this is a bit beyond my comfort zone to do solo so if @ChrisCrossQS would like to help or if @hediet could provide just support on the architecture and planning, I'm down to make this happen.

It's my favorite extension and I'm over vscode's pseudo open source enough that I'm ready to jump ship.

**Comment by HansUXdev** [comment]
@hediet are you able to publish the scode-drawio.vsix file by chance?

**Comment by HansUXdev** [comment]
@hediet I think this can be closed, I managed to publish it on the [open-vsx](https://open-vsx.org/extension/hediet/vscode-drawio). Took me a while to figure out how to compile it. I had to install bufferutil & utf-8-validate, run the pre-build than the build than I just ran `ovsx create-namespace hediet` and `ovsx publish`.

Also @ChrisCrossQS I just tested it on codium and it works like a charm!
It doesn't work in gitPod for some reason I have yet to figure out.
It throws the following error: `Integration failed: o.window.registerCustomEditorProvider is not a function.`

**Comment by hediet** [comment]
@HansUXdev thanks ;) 
BTW this is what I meant with

> Sadly, Theia does not seem to support custom editors yet. So this extension is not compatible with theia anyways

**Comment by hediet** [comment]
Also, compiling should not be difficult. There is a github action that builds every commit for each platform, ensuring that everything builds properly!

**Comment by hediet** [comment]
>  I managed to publish it on the open-vsx. T

Argh, you didn't use the same workflow as I do for preparing the extension... You published the dev-build with version 999! This will stay the newest version forever. Please delete the version and have a look at the github actions on how to publish it. Alternatively, you can open a PR and change the github action to publish it automatically to open vsx.

**Comment by HansUXdev** [comment]
This was the first extension I've worked with so my bad 😓 .
Since then I've publish a few other smaller ones.

I'll sort this out, however to be fair the culprit is the package.json because I didn't check the package version. 

https://github.com/hediet/vscode-drawio/blob/6376917d1c7702a7cf53b33fa3408a27219c786b/package.json#L6

**Comment by HansUXdev** [comment]
It's been unpublished now. I need to figure out how to use github actions to build it correctly.
I also need to figure out how to run your other extension to visualize algorithms.

**Comment by hediet** [comment]
Thanks! Have a look at the publish github action. It runs a script first that uses the version from the changelog. The package json version is that high so that when debugging it, it always overrides any installed version.

**Comment by MarcusLlewellyn** [comment]
It appears that @HansUXdev may have unlisted rather than removed his build of this extension on open-vsx. I'm using the Draw.io extension with code-server, and when I attempt to install the VSIX myself, it keeps trying to update it to version 999.0.0-alpha.

**Comment by HansUXdev** [comment]
@MarcusLlewellyn I'm not sure why that is happening. Did you download it before all this?

Also to clarify, I don't think you can directly unlist or unpublished it on open-vsx. I had to ask the maintainers directly on [gitter](https://gitter.im/eclipse/openvsx). @hediet may need to request direct access to the namespace.

I haven't had the need or interest in learning how to use github actions and honestly I don't think that will change so, if gitpod adds support for custom methods, I may end up republishing a forked version under a different namespace with package.json set to 1.0.0 and manually pull/maintain the open-vsx version.

 But other than that, I'm going hands off on this because I need to focus on a few other projects.

**Comment by nopeslide** [comment]
@hediet 
it doesn't look like you claimed your open-vsx namespace.
if you don't want others to publish under your name, I recommend claiming it.
this works by opening an issue in their repository: [open issue](https://github.com/eclipse/open-vsx.org/issues/new/choose).
publishing is very similar to the ms marketplace

**Comment by hediet** [comment]
[This](https://github.com/eclipse/open-vsx.org/issues/205) is a blocker.
