### ISSUE TITLE
Automatically open custom libraries on extension start

### ISSUE THREAD

**Issue by rhofer** [hediet/vscode-drawio#17]
Would it be possible to add an extension setting which would allow to configure a `path` to a location in current folder where libraries are stored?
```xml
Hediet > Vscode-drawio: Library-path
# Path to my awesome libraries
"my-drawio-libraries"
```

This would allow to separately publish self-created libraries, then to download them into `my-drawio-libraries` and then afterwards to open a `*.drawio` or `*.drawio.png` file for editing, where Vscode-drawio extension would automatically load all libraries from the given folder.

(With the current extension, it is also possible to load libraries but only file per file. And whenever another file.drawio is opened, the extension is restarted and the libraries need to be loaded again.)

**Comment by hediet** [comment]
That sounds useful. Do you have a sample library file?

**Comment by rhofer** [comment]
Created with draw.io desktop. Zip comprises TestLibrary.xml

[TestLibrary.zip](https://github.com/hediet/vscode-drawio/files/4612122/TestLibrary.zip)

**Comment by rhofer** [comment]
I tested with 0.4.0, adding the following to settings.json in my project's local storage (`.vscode` folder):

```json
    "hediet.vscode-drawio.local-storage": {
        ".drawio-config": {
            "customLibraries": [
                "L.scratchpad",
                "Uhttps%3A%2F%2Fjgraph.github.io%2Fdrawio-libs%2Flibs%2Ftemplates.xml"
            ]
        }
    }
```
So far, this works with remote URL.

Do you have an idea how to specify a file on local storage /harddrive ?

**Comment by hediet** [comment]
You could misuse the scratchpad until I properly support it in my extension (which will be soon).

**Comment by rhofer** [comment]
I further tried to customize by editing the workspace's `settings.json` found in `.vscode` folder. There I added:
```json
  "customPresetColors": [
    "66CCFF",
    "FF6600",
    "99FF99",
    "FFFF00",
    "FFCCFF",
    "FFCC66",
    "E8EDF7"
  ]
```

1. This never arrives in the extension as changed presetColors in the palette
2. Despite of having it added to the workspace's settings.json only, it is somehow propagated back to the users global settings `../AppData/Roaming/Codes/User/settings.json` (as windows user)

As I wrote in #30 it would be good to have the extensions config as part of the repository (workspace). This would allow to configure draw.io per repo. E.g. if a specific repo requires to follow some docu guidelines which includes graphical styles. Btw, this is also the major argument mentioned in https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-

Beyond this issue, I'd ask you to generally think about how to handle workspace sepcific demands.

**Comment by hediet** [comment]
> As I wrote in #30 it would be good to have the extensions config as part of the repository (workspace). This would allow to configure draw.io per repo. E.g. if a specific repo requires to follow some docu guidelines which includes graphical styles. Btw, this is also the major argument mentioned in https://desk.draw.io/support/solutions/articles/16000058316-how-to-configure-draw-io-
Beyond this issue, I'd ask you to generally think about how to handle workspace sepcific demands.

I thought of that too. I created an issue for that (#40). Would that solve your use case?

> Despite of having it added to the workspace's settings.json only, it is somehow propagated back to the users global settings ../AppData/Roaming/Codes/User/settings.json (as windows user)

Yeah if you do that funny things happen: The extension will read the config from the workspace settings, but write the new config back to the global settings.

> customPresetColors

Can you send me the entire entry of your settings.json file? Also, please note that the localStorage setting does not match the drawio config! You might not be able to set customPresetColors through the localStorage.

**Comment by rhofer** [comment]
[settings.json.txt](https://github.com/hediet/vscode-drawio/files/4642932/settings.json.txt)

**Comment by rhofer** [comment]
> Also, please note that the localStorage setting does not match the drawio config! You might not be able to set customPresetColors through the localStorage.

Ok, does this mean that it needs to be explicitly coded what shall be taken from localStorage settings and then inject into drawio embedded? (Hence, it's about coding this and not only kind of "passing though" what is configured?)

Yes, will have a look at #40

**Comment by hediet** [comment]
It might not work this way. What do you think of making localStorage readable/editable in the first place?

It allows to configure some things that could not be configured before (like fonts), but people like you might try to configure something that cannot be configured through localStorage and possibly waste their time doing this.
The description already reads that changing localStorage manually is not supported :D Maybe I should base64 encode it.

I think, generally, it's better to not support something at all rather than inoffically supporting it, but introducing behavior that may lead to wasting time. Apple understood this pretty well :D

**Comment by hediet** [comment]
> Ok, does this mean that it needs to be explicitly coded what shall be taken from localStorage settings and then inject into drawio embedded?

I think draw.io always gives precedence to what you configure using the configure event over its internal config in the localStorage. I only pass compressXml: false there and sync the localStorage.

It might be better to add several settings to this extension to send a more specific configure event rather than editing the localStorage directly.

**Comment by rhofer** [comment]
> I think, generally, it's better to not support something at all rather than inoffically supporting it, but introducing behavior that may lead to wasting time.

Yes, I agree. But maybe I can support to make it happen e.g. for configurability / customizing.

> ... marketplace reviews and stars ...

Yes, you need to live with it. To publish something always means to expose oneself. Personally to me it's the opposite to having 5 stars always. Giving 5 stars without comment is meaningless. Giving 1 star with a specific feedback is more important. When downloading an extension I primarily go to the lower ratings and read the feedback and especially the answer to it. If the question was reasonable and it applies to my use case, I might not use the extension. Quite often people place crappy complaints what is obvious immediately.

More important is how developer reacts on this, what brings me to always look up the repository (e.g. GitHub). If issues are actively treated, community participates, etc., this is to me the rating I'm looking for ... software never is perfect.

Besides this a number of over 34k downloads is also saying something.

And from use case / workflow point of view, I'd expect drawio embedded e.g. as vsc extension **is** tailored in functionality to the workflow to be achieved. For everything else, I have drawio desktop. Hence, don't worry in tailoring off some features. 

In my opinion the core workflow / happy path should be: have your sw repo, creae/open a picture, edit in draw.io extension, save/close, kick-off pipeline, publish your rendered text with included pictures ...
And I thing, the configuration aspects we discuss here, is exactly to support this workflow with local workspace's specific needs.

**Comment by hediet** [comment]
Thanks for your thoughts!

> If the question was reasonable and it applies to my use case, I might not use the extension.

This is very reasonable and it is very reasonable too to write 1/5 star reviews if you want to prevent somebody to waste their time with the reviewed extension. 

However, clearly not all people are reasonable. Also, if you see an extension with an average 1/5 rating, you probably think it is crap.

This happened to my debug visualizer extension:
![image](https://user-images.githubusercontent.com/2931520/82206193-10de1780-9908-11ea-8522-675249646c8e.png)

After putting a significant amount of work into this extension (much more than I put into vscode-drawio), a guy gave it 1/5 stars (he seemingly didn't understand how to use it) and because his review was the only one the average rating became the same for at least a week. This does not look good if somebody screens your open source work and only sees the average rating...

Anyways. Implementing the configuration options for this extension won't take long (I have a pretty precise picture of what I need to do) and I don't think it would be efficient if you would help me on this issue, but thanks for the offer ;)

If you are interested in contributing/helping, you could try to figure out how to get rid of the inner iframe :D This is a serious problem (required to make VS Code shortcuts work when the drawio editor is focused) and quite time consuming to figure out ;)

**Comment by hediet** [comment]
Support for custom libraries is now implemented in the insiders build that you can install from the marketplace.
