### ISSUE TITLE
can‘t export file

### ISSUE THREAD

**Issue by cy55120** [hediet/vscode-drawio#34]
export file to PDF , can't exported ,It's gone in a flash.

VSCode Version:1.45.1
VSCode-drawio Version:1.0.2

**Comment by cy55120** [comment]
**Click the button and the window disappears**

![image](https://user-images.githubusercontent.com/28081361/82008285-d160c280-969e-11ea-87f5-92d0530c0aae.png)

**Comment by 1751200** [comment]
I encountered the same problem with my macOS X, and cannot export any form of file (*.png, *.svg...).

VScode Version: 1.45.1

**Comment by hediet** [comment]
Why do you want to export a PDF?

**Comment by hediet** [comment]
If you rename your *.drawio diagram to *.drawio.svg, it will be converted to a SVG automatically the next time you save changes.

Because export does not work and I don't think exporting things is a great user experience, I will rather try to hide the export options alltogether (#22).

If you think it is a must have, please convince me ;) A cli should be the way to go for exports.

**Comment by traits** [comment]
>  I don't think exporting things is a great user experience

This is an interesting, but IMO rather rare point of view. The original itself has this option not without reason (even if poorly implemented as in the case of svg).

**Comment by TestUser013** [comment]
> If you think it is a must have, please convince me ;) 

PDF format is used for sharing document in read-only mode.  What benefit of your extension if you provide reduced version of drawio-desktop?

**Comment by hediet** [comment]
@TestUser013 feel free to open a PR! I think this extension offers a lot of benefits even without pdf export.
