### ISSUE TITLE
Some icons are missing! They show up as blanks; most notably all the Atlassian logos are missing

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#53]
Uh oh, tiny issue... Some icons are missing! They show up as blanks; most notably all the Atlassian logos are missing. I confirmed that the svg's were present in the `drawio` source folder; but the logos are refusing to show up. Any idea?

![image](https://user-images.githubusercontent.com/3169104/82544975-3ceed800-9b56-11ea-82f3-ca9a6fffe56c.png)

It's not just these, the Docker image is also missing (which is part of a MS Azure pack according to the source code). Is the drawio master just broken, or is there something I can do?

_Originally posted by @MagicLegend in https://github.com/hediet/vscode-drawio/issues/51#issuecomment-631985751_

**Comment by MagicLegend** [comment]
I have spent some time digging around in the source code; but I don't see any issue. Can you reproduce this when you package the extension?

**Comment by hediet** [comment]
I'll try it tomorrow! Thanks for the research ;)

**Comment by MagicLegend** [comment]
I can confirm that when you save an `.svg` with an broken image on insiders; and reopen it with the published version in normal vscode that the logo shows up again. In the svg the logo is stored as follows:

```
<image x="146.5" y="369.5" width="66" height="66" xlink:href="data://text/data://text/img/lib/atlassian/Atlassian_Logo.svg"/>
```

I'm not sure where that path is supposed to lead; since it's relative. the `text/` folder doesn't seem to exist? Anyhow; I still think it has to do something with an update of `drawio`. The preview of icons is also changed/broken (it is supposed to zoom in on the iconmap, but it doesn't now). Can you confirm this too?

**Comment by MagicLegend** [comment]
Hmm, adding working images to the drawing I start to see a pattern. All images that don't work are references to `.svg` files themselves. Note that the used URI for those images can never resolve, since the `data://text/` is double here. Other icons from the `Web Icons` or `Atlassian` packs are being inserted as raw `svg` xml; or as HTML:

```
<g transform="translate(-0.5 -0.5)">
            <switch>
                <foreignObject style="overflow: visible; text-align: left;" pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility">
                    <div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 38px; height: 1px; padding-top: 416px; margin-left: 261px;">
                        <div style="box-sizing: border-box; font-size: 0; text-align: center; ">
                            <div style="display: inline-block; font-size: 14px; font-family: Helvetica; color: #ffffff; line-height: 1.2; pointer-events: all; font-weight: bold; white-space: normal; word-wrap: normal; ">
                                &lt;/&gt;
                            </div>
                        </div>
                    </div>
                </foreignObject>
                <text x="280" y="420" fill="#ffffff" font-family="Helvetica" font-size="14px" text-anchor="middle" font-weight="bold">
                    &lt;/&gt;
                </text>
            </switch>
        </g>
```

=

![image](https://user-images.githubusercontent.com/3169104/82657091-0e8bfe00-9c25-11ea-89a7-69c632f3b9b4.png)

Does this extension do anything with the file paths; or is this something ready to escalate to Drawio themselves?

**Comment by hediet** [comment]
Hi, I'll have a look at it tomorrow. Does this happen on draw.io alone? I. E. when not using my extension?
________________________________

**Comment by MagicLegend** [comment]
Well, I couldn't figure out how to actually run the included drawio without the extension. Since the drawio-desktop version is mismatched with the one here; I figured that it wasn't identical. It would also add a wrapper around drawio, which I can imagine could resolve the issue.

Do you know how I could run the included drawio without the wrapper of the extension? Feel free to answer tomorrow ;-)

**Comment by hediet** [comment]
I mean does it happen with the draw.io website?
________________________________

**Comment by MagicLegend** [comment]
Ah yes. Didn't test that yet; good point.

The same does not happen, because it references an online image:

```
<image x="-0.5" y="-0.5" width="66" height="66" xlink:href="https://app.diagrams.net/img/lib/atlassian/Atlassian_Logo.svg"/>
```

Note that the behaviour of the website version and the extension version of referencing an `.svg` file and using the aforementioned HTML object is identical.

**Comment by MagicLegend** [comment]
I can confirm that this issue persists on c42d865 (current insiders build, v0.6.1).

**Comment by hediet** [comment]
I did some research.

This is the drawio xml node:
```xml
<mxCell id="11" value="" style="image;image=img/lib/atlassian/Atlassian_Logo.svg;" vertex="1" parent="1">
    <mxGeometry x="160" y="540" width="166" height="170" as="geometry"/>
</mxCell>
```

This is the svg node when exporting with my vscode extension:
```xml
<image xmlns="http://www.w3.org/2000/svg" x="119.5" y="519.5" width="166" height="170" xmlns:xlink="http://www.w3.org/1999/xlink"
  xlink:href="data://text/data://text/img/lib/atlassian/Atlassian_Logo.svg"/>
```

And this is the svg node when exporting with https://draw.io:
```xml
<image xmlns="http://www.w3.org/2000/svg" x="-0.5" y="239.5" width="446" height="280" xmlns:xlink="http://www.w3.org/1999/xlink"
  xlink:href="https://app.diagrams.net/img/lib/atlassian/Atlassian_Logo.svg"/>
```

Those images are referenced relatively to the hosting domain. This does not make sense for the VS Code extension (where the domain is `data://...`).
Also, this is very dangerous: The exported SVG will stop working once `app.diagrams.net` is offline or if you don't have internet.

I played around with setting these:
```js
window.GRAPH_IMAGE_PATH = "https://app.diagrams.net/img";
window.DRAWIO_BASE_URL = "https://app.diagrams.net";
```
But I didn't get it working.

I don't think I will spend much more time trying to fix this as I don't think much about this feature...
But I will gladly accept PRs!

**Comment by ebousse** [comment]
Same problem with the "Clipart" shapes :
![Capture d’écran de 2020-05-27 10-34-45](https://user-images.githubusercontent.com/5868014/82996759-be86b000-a005-11ea-8c1d-759c473a8733.png)

**Comment by hediet** [comment]
If this feature is really important for you, you can consider to support me on github sponsors!
Since I don't need this feature, I already spent like 2 hours debugging this and there are other features that are a lot more fun to implement, I don't plan to fix this soon just for fun.

I happily accept PRs though.

**Comment by ebousse** [comment]
>  Since I don't need this feature, I already spent like 2 hours debugging this and there are other features that are a lot more fun to implement, I don't plan to fix this soon just for fun.

No problem, just wanted to add my observation to the thread :). I'm already very glad you made this very neat extension :+1: .

**Comment by razvangoga** [comment]
Just to add my observations on this: the problem seems to have been introduced after v0.4 (i've reverted back to it and all works as expected). Unfortunetly i don't see 0.5 or 0.5.1 in the previus versions list to narrow it down even more, but if i would venture a guess it would be due to this change : **_- Does not spawn an http server anymore to host Draw.io_** from 0.5

![image](https://user-images.githubusercontent.com/1067494/83051370-3bd61300-a04e-11ea-8943-a8b1a2965949.png)
