### ISSUE TITLE
Support PNG Export

### ISSUE THREAD

**Issue by hediet** [hediet/vscode-drawio#56]
It would be useful if Draw.io diagrams could be exported to PNG files.

**Comment by LarryZhao0616** [comment]
why removed this feature?

if the reason is 'how do I teach users that they don't need to export to png everytime, but can just directly edit the png file with this drawio extension?'. my response would be: I don't care.

I chose to use this extension because I can edit drawio locally in my vscode with this extension. drawio has the basic feature of supporting exporting png files. If you remove it and try to 'teach' users use your pure png editor, then this extension should be named 'genuis-png-editor' instead of 'vscode-drawio'.

**Comment by hediet** [comment]
As you can see, this feature has been released to insiders:

![image](https://user-images.githubusercontent.com/2931520/82802457-39718e80-9e7f-11ea-9fef-690d8bbb09e3.png)

**Comment by LarryZhao0616** [comment]
> As you can see, this feature has been released to insiders:
> 
> ![image](https://user-images.githubusercontent.com/2931520/82802457-39718e80-9e7f-11ea-9fef-690d8bbb09e3.png)

Oops...

Forgive me for ignoring this important log, hope the release day is coming soon. BTW, Great work! I love this extension.

**Comment by hediet** [comment]
You could directly install the Insiders Build of this extension from the marketplace! If it works, I can fully release this feature.
