### ISSUE TITLE
[feature request] Open new editor from command menu

### ISSUE THREAD

**Issue by TestUser013** [hediet/vscode-drawio#9]
Could you please add possibility to open drawio editor directly from command palette.

**Comment by hediet** [comment]
Hmm, I looked into it, but I don't know how to do it (I would need to create a virtual custom document for that, I don't know whether this is support by VS Code).

You would have to specify the target anyways in the end, so it's not a big time saver.
If you convince me otherwise, I'll reopen this issue!
